# Generated by Django 5.1.2 on 2024-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('scheduler', 'Scheduler'), ('viewer', 'Viewer'), ('driver', 'Driver'), ('passenger', 'Passenger')], default='Viewer', max_length=20),
        ),
    ]
