# Generated by Django 5.1.2 on 2024-10-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.AutoField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
